# Generated by Django 4.2.1 on 2023-06-11 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participants",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="course.room",
            ),
        ),
        migrations.AddField(
            model_name="participants",
            name="user_download_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participants",
            name="user_email_sent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Enrollment",
        ),
    ]
