# Generated by Django 4.2.1 on 2023-06-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_participants_room_participants_user_download_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("image", "Image"),
                    ("audio", "Audio"),
                    ("video", "Video"),
                ],
                default="null",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="user_download_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resource",
            name="user_email_sent",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
