# Generated by Django 4.2.1 on 2023-06-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_resource_file_type_resource_user_download_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("image", "Image"),
                    ("audio", "Audio"),
                    ("video", "Video"),
                ],
                max_length=10,
            ),
        ),
    ]
