# Generated by Django 4.2.1 on 2023-06-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_alter_resource_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("image", "Image"),
                    ("audio", "Audio"),
                    ("video", "Video"),
                ],
                default="null",
                max_length=10,
            ),
        ),
    ]
