# Generated by Django 4.2.1 on 2023-06-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_alter_resource_file_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoStreamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("uid", models.CharField(max_length=1000)),
                ("room_name", models.CharField(max_length=200)),
                ("insession", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="resource",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("image", "Image"),
                    ("audio", "Audio"),
                    ("video", "Video"),
                    ("link", "link"),
                ],
                default="null",
                max_length=10,
            ),
        ),
    ]
