# Generated by Django 4.2.1 on 2023-06-12 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="end_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
