# Generated by Django 4.2.1 on 2023-06-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_quiz_end_date_quiz_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
    ]
