# Generated by Django 4.2.1 on 2023-06-12 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_alter_resource_file_type"),
        ("event", "0003_alter_event_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.course"
            ),
        ),
    ]
