from django.shortcuts import render
from course.models import Course, Announcement, Participants

def announcementPage(request, pk):
    """
    Render the announcement page for a specific course.

    This view function retrieves the necessary data to display the announcement page for a particular course.
    It fetches the participant's enrolled courses, retrieves the course based on the provided primary key (pk),
    and retrieves the announcements associated with the course. The announcements are ordered by their 'updated' field
    in descending order.

    Parameters:
    - request: The HTTP request object generated by the user's interaction with the web application.
    - pk: The primary key of the course for which the announcement page is being rendered.

    Returns:
    - A rendered HTML template displaying the announcement page with the course details and associated announcements.

    """

    # Retrieve the currently logged-in employee
    employee = request.user
    
    # Get all courses enrolled by the user
    participants = Participants.objects.filter(user=employee)
    courses = [participant.course for participant in participants]
    

    # Retrieve the course based on the provided primary key
    course = Course.objects.get(pk=pk)

    # Retrieve the announcements associated with the course
    announcements = Announcement.objects.filter(course=course).order_by('-updated')

    # Prepare the context data to be passed to the template
    context = {
        'course': course,
        'announcements': announcements,
        'courses': courses
    }

    # Render the announcement page template with the context data
    return render(request, "page/announcement_page.html", context)
