from django.shortcuts import render
from myapp.models import User

def profile(request, pk):
    """
    Render the profile page for a user.

    This view function retrieves the user profile data based on the provided primary key (pk) and renders the 
    profile page template with the user profile as context.

    Parameters:
    - request: The HTTP request object generated by the user's interaction with the web application.
    - pk: The primary key of the user whose profile is being accessed.

    Returns:
    - The function renders the profile page template with the user profile as context.

    """

    # Retrieve the user profile based on the provided primary key
    user_profile = User.objects.get(id=pk)

    # Prepare the context data
    context = {'user_profile': user_profile}

    # Render the profile page template with the context data
    return render(request, "page/profile.html", context)
