from django.shortcuts import render, get_object_or_404
from course.models import Course, Room, Participants

# room page
def roomPage(request, pk):
    """
    Render the room page for a course.

    This view function retrieves the necessary data to display the room page for a specific course. It fetches the
    participants of the course, retrieves the rooms associated with the course, and prepares the context data for rendering
    the room page template.

    Parameters:
    - request: The HTTP request object generated by the user's interaction with the web application.
    - pk: The primary key of the course for which the room page is being accessed.

    Returns:
    - The function renders the room page template with the necessary context data.

    """
    employee = request.user
    
    participants = Participants.objects.filter(user=employee)
    courses = [participant.course for participant in participants]
    
    myCourse = Course.objects.filter(pk=pk)
    
    # Retrieve the course based on the provided pk
    course = Course.objects.get(id=pk)

    # Retrieve the announcements associated with the course
    rooms = Room.objects.filter(course__in=myCourse)

    context = {
        'course': course,
        'rooms': rooms,
        'courses': courses,
    }

    return render(request, "page/room_page.html", context)